---

name: Creating the infrastructure

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Amazon ECR
    env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_ecr_repository_name: ${{ secrets.ECR_REPOSITORY_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev

      # use Terraform in the Runner environment
      - name: Use latest Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Using terraform init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"

      - name: Using terraform plan
        run: terraform plan -no-color

      # create ECR Repository
      - name: Create ECR Repository
        run: terraform apply -auto-approve