---

name: Creating the infrastructure

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Declare infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev

      # use Terraform in the Runner environment
      - name: Use latest Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Using terraform init
        run: terraform init

      - name: Using terraform plan
        run: terraform plan -no-color
        env:
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # create ECR Repository
      - name: Create ECR Repository
        run: terraform apply
        env:
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}