---

name: Packer

on:
  push:
    branches:
      - dev

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: wordpress-image.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: wordpress-image.json

      # use Packer in the Runner environment
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1


      # build artifact
      - name: Build Artifact
        run: packer build -color=false -on-error=abort wordpress-image.json
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          GITHUB_PASS: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          DOCKER_REPOSITORY: "docker.pkg.github.com"

      # additional steps to process artifacts