---

name: Deleting the infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: AWS infrastructure
    env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        TF_VAR_ecr_repository_name: ${{ secrets.ECR_REPOSITORY_NAME }}
        TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
        TF_VAR_rds_name: ${{ secrets.RDS_NAME }}
        TF_VAR_rds_user: ${{ secrets.RDS_USER }}
        TF_VAR_rds_pass: ${{ secrets.RDS_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      # use Terraform in the Runner environment
      - name: Use latest Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Using terraform init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
          terraform/environments

      - name: Using terraform destroy
        run: terraform destroy -auto-approve terraform/environments