---

name: Generating Wordpress Image

on:
  push:
    branches:
      - dev

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build with Packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: wordpress-image.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: wordpress-image.json

      # make GitHub Repository (owner/repository name) in lowercase
      - name: GitHub Username in lowercase
        run: |
          echo GITHUB_ACTOR=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      # use Packer in the Runner environment
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      # build artifact
      - name: Build Artifact
        run: packer build -color=false -on-error=abort wordpress-image.json
        env:
          PACKER_LOG: 1
          GITHUB_PASS: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ env.GITHUB_ACTOR }}
          DOCKER_REPOSITORY: "ghcr.io"

      # additional steps to process artifacts

